# Generated by Django 4.1 on 2022-09-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('height', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
